name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository kernel"
        required: true
        default: "https://github.com/ZGSYet/NekoPoi-Kranul.git"

      branch:
        description: "Branch yang ingin dibuild"
        required: true
        default: "test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y \
            git bc bison flex libssl-dev make automake build-essential \
            curl zip clang lld gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
            
      - name: Clone Selected Repo
        run: |
          git clone --depth=1 \
          --branch ${{ github.event.inputs.branch }} \
          ${{ github.event.inputs.repo }} source

      - name: Check LLVM
        run: |
          clang --version
          llvm-objdump --version
          llvm-nm --version
          llvm-ar --version

      - name: Build Kernel
        run: |
          cd source
          chmod +x build.sh
          ./build.sh
