name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository kernel"
        required: true
        default: "https://github.com/ZGSYet/NekoPoi-Kranul.git"
      branch:
        description: "Branch yang ingin dibuild"
        required: true
        default: "test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Selected Repo
        run: |
          git clone --depth=1 --branch ${{ github.event.inputs.branch }} ${{ github.event.inputs.repo }} source     

      - name: Build Kernel
        run: |
          cd source
          chmod +x build.sh
          ./build.sh

